apiVersion: batch/v1
kind: CronJob
metadata:
  name: rc-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-resource-consumer
            image: buildpack-deps:curl
            command:
            - /bin/sh
            - -ec
            - curl --data "millicores=600&durationSec=500" http://resource-consumer/ConsumeCPU
          restartPolicy: OnFailure